name: Run Automation Tests

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  run-automation-test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v2

    - name: Set up Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18.20.4'

    

    - name: Run Automation Test
      run: |
        node ./index.cjs web --endPoint "https://stg-gateway.quinnox.info:8243" \
        --username "dakoki9526@massefm.com" \
        --passcode "UGFzc3dvcmRAMTIzCg==" \
        --teamName "CTC End To End" \
        --projectName "Healer Project" \
        --suiteName "Test" \
        --parameterFileSource "DATATABLE" \
        --browserOS "windows" \
        --browser "Chrome" \
        --onErrorContinue "true" \
        --emailId "sachina@quinnox.com" \
        --env "global"
